# Generated by Django 4.1.2 on 2022-10-13 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CITY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CITY_NAME', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='COUNTRY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COUNTRY_NAME', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ROLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER_TYPENAME', models.CharField(choices=[('1', 'USER'), ('2', 'SELLER'), ('3', 'ADMIN')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='USER_DETAIL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('U_NAME', models.CharField(max_length=30)),
                ('U_PASSWORD', models.IntegerField()),
                ('U_EMAIL', models.EmailField(max_length=254)),
                ('U_PHONE', models.IntegerField()),
                ('U_STATUS', models.CharField(choices=[('0', 'ACTIVE'), ('1', 'INACTIVE')], max_length=50)),
                ('U_TYPE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.role')),
            ],
        ),
        migrations.CreateModel(
            name='USER_ADDRESS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BUILDING_NAME', models.CharField(max_length=40)),
                ('STREET_NAME', models.CharField(max_length=30)),
                ('PIN_CODE', models.IntegerField()),
                ('CITY_NAME_ONLY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.city')),
                ('U_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_detail')),
            ],
        ),
        migrations.CreateModel(
            name='STATE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STATE_NAME', models.CharField(max_length=40)),
                ('COUNTRY_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.country')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='State_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.state'),
        ),
    ]
