# Generated by Django 4.1.2 on 2022-10-13 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BANK_DETAIL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BANK_NAME', models.CharField(max_length=40)),
                ('DIGIT_N0', models.IntegerField()),
                ('END_MONTH', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')])),
                ('END_YEAR', models.IntegerField(choices=[('1', '2022'), ('2', '2023'), ('3', '2024'), ('4', '2025'), ('5', '2026'), ('6', '2027'), ('7', '2028'), ('8', '2029'), ('9', '2030')])),
                ('U_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_detail')),
            ],
        ),
    ]
